import Image from 'next/image';
import Link from 'next/link';

export const dynamic = 'force-dynamic';

export default function LandingPage() {
  return (
    <main>
      <section className="mx-auto max-w-3xl px-6 py-20">
        <h1 className="text-5xl font-semibold tracking-tight">
          Turn YouTube into notes you&apos;ll actually re-read.
        </h1>
        <p className="mt-6 text-lg text-[var(--muted-foreground)]">
          Paste a URL. Get a structured Markdown file — cliff notes, quotes with timestamps, and
          further reading — dropped straight into your Obsidian vault or Notion database.
        </p>

        <div className="mt-8 flex gap-3">
          <Link
            href="/sign-up"
            className="rounded-md bg-[var(--primary)] text-[var(--primary-foreground)] px-5 py-2.5 font-medium"
          >
            Try it free
          </Link>
        </div>

        <div className="mt-20 grid grid-cols-1 sm:grid-cols-3 gap-6">
          <Feature
            title="Writes to your vault, not another silo"
            body="A .md file with YAML frontmatter. Drop it in Obsidian, Notion, Logseq, or any folder of Markdown. No lock-in. Your notes live in your filesystem, indexed by the tool you already trust."
          />
          <Feature
            title="Timestamped quotes link back to YouTube"
            body="Every quoted passage in the summary includes a clickable timestamp. One click takes you back to the exact moment in the video — verify a claim, re-listen, or dig deeper."
          />
          <Feature
            title="Open-source core, bring your own key"
            body="The CLI, self-host backend, and Obsidian plugin are on GitHub. Run it yourself with a Gemini or Claude API key. Or skip the setup and use the hosted tier for $9.99/mo."
          />
        </div>
      </section>

      <section className="mx-auto max-w-5xl px-6 py-20">
        <h2 className="text-3xl font-semibold tracking-tight">What you actually get</h2>
        <p className="mt-3 text-[var(--muted-foreground)]">
          Paste a URL. Thirty seconds later, this is in your vault.
        </p>

        <div className="mt-10 grid grid-cols-1 md:grid-cols-2 gap-6">
          <ScreenshotPair
            light="/marketing/obsidian-frontmatter-light.webp"
            dark="/marketing/obsidian-frontmatter-dark.webp"
            lightWidth={2400}
            lightHeight={1462}
            darkWidth={2400}
            darkHeight={1431}
            alt="An Obsidian note generated by Kura, showing YAML frontmatter with title, channel, URL, tags, and a rendered cliff-notes outline."
          />
          <ScreenshotPair
            light="/marketing/obsidian-quotes-light.webp"
            dark="/marketing/obsidian-quotes-dark.webp"
            lightWidth={2400}
            lightHeight={1438}
            darkWidth={2400}
            darkHeight={1429}
            alt="The same Obsidian note, scrolled to the Quotes section, showing block quotes with clickable timestamped links back to the YouTube video."
          />
        </div>
      </section>

      <section className="mx-auto max-w-5xl px-6 py-20">
        <h2 className="text-3xl font-semibold tracking-tight">From fifteen minutes to thirty seconds</h2>
        <div className="mt-10 grid grid-cols-1 md:grid-cols-2 gap-8">
          <Workflow
            label="Manual workflow"
            steps={[
              'Open YouTube, enable captions.',
              'Copy the transcript from the CC panel.',
              'Paste into ChatGPT, write a prompt.',
              'Review, fix errors, trim irrelevant sections.',
              'Copy output into your vault.',
              'Add frontmatter, tags, source URL by hand.',
              'Link back to video timestamps manually.',
            ]}
            total="~15 min"
          />
          <Workflow
            label="With Kura"
            steps={['Paste URL.', 'Pick a template.', 'Download or sync.']}
            total="~30 sec"
          />
        </div>
      </section>

      <section className="mx-auto max-w-2xl px-6 py-20">
        <h2 className="text-3xl font-semibold tracking-tight">Open-source core</h2>
        <div className="mt-6 flex flex-wrap gap-3">
          <a
            href="https://github.com/zhashkevych/kura"
            className="inline-block"
            aria-label="Kura GitHub stars"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="https://img.shields.io/github/stars/zhashkevych/kura?style=flat-square&label=Stars"
              alt="GitHub stars"
              loading="lazy"
              height={20}
            />
          </a>
          <a
            href="https://github.com/zhashkevych/kura/blob/main/LICENSE"
            className="inline-block"
            aria-label="Kura license"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="https://img.shields.io/github/license/zhashkevych/kura?style=flat-square"
              alt="License"
              loading="lazy"
              height={20}
            />
          </a>
        </div>
        <p className="mt-6 text-[var(--muted-foreground)]">
          The transcript pipeline, Markdown renderer, Obsidian plugin, and self-host backend are
          on GitHub. Run the whole thing on your own hardware with your own Gemini or Claude API
          key. Use the hosted tier if you&apos;d rather not. Both paths produce the same Markdown.
        </p>
        <div className="mt-6 flex flex-wrap gap-6 text-sm">
          <a
            href="https://github.com/zhashkevych/kura"
            className="font-medium underline-offset-4 hover:underline"
          >
            View on GitHub →
          </a>
          <a
            href="https://github.com/zhashkevych/kura#self-host"
            className="text-[var(--muted-foreground)] underline-offset-4 hover:underline"
          >
            Self-host guide →
          </a>
        </div>
      </section>

      <section className="mx-auto max-w-5xl px-6 py-20">
        <h2 className="text-3xl font-semibold tracking-tight">Pricing</h2>
        <div className="mt-10 grid grid-cols-1 md:grid-cols-2 gap-6">
          <PricingCard
            name="Free"
            price="$0"
            tagline="For trying it out."
            bullets={[
              '10 summaries per month',
              'All three templates',
              'Markdown export',
              'Hosted, no setup',
            ]}
            ctaLabel="Try it free →"
            ctaHref="/sign-up"
            emphasized={false}
          />
          <PricingCard
            name="Pro"
            price="$9.99"
            priceSuffix="/month"
            priceFootnote="or $84/year"
            tagline="For daily use."
            bullets={[
              'Unlimited summaries',
              'Channel subscriptions (coming soon)',
              'Notion sync',
              'Priority support',
            ]}
            ctaLabel="Start free trial →"
            ctaHref="/sign-up"
            emphasized
          />
        </div>
        <p className="mt-6 text-center text-sm text-[var(--muted-foreground)]">
          Or self-host the open-source core with your own API key — free forever.
        </p>
      </section>
    </main>
  );
}

function Feature({ title, body }: { title: string; body: string }) {
  return (
    <div className="rounded-lg border border-[var(--border)] p-4">
      <h3 className="font-semibold">{title}</h3>
      <p className="mt-2 text-sm text-[var(--muted-foreground)]">{body}</p>
    </div>
  );
}

function PricingCard({
  name,
  price,
  priceSuffix,
  priceFootnote,
  tagline,
  bullets,
  ctaLabel,
  ctaHref,
  emphasized,
}: {
  name: string;
  price: string;
  priceSuffix?: string;
  priceFootnote?: string;
  tagline: string;
  bullets: string[];
  ctaLabel: string;
  ctaHref: string;
  emphasized: boolean;
}) {
  return (
    <div
      className={
        'flex h-full flex-col rounded-lg p-6 ' +
        (emphasized
          ? 'border-2 border-[var(--foreground)]'
          : 'border border-[var(--border)]')
      }
    >
      <div className="text-sm font-medium uppercase tracking-wide text-[var(--muted-foreground)]">
        {name}
      </div>
      <div className="mt-4 flex items-baseline gap-1">
        <span className="text-4xl font-semibold tracking-tight">{price}</span>
        {priceSuffix ? (
          <span className="text-[var(--muted-foreground)]">{priceSuffix}</span>
        ) : null}
      </div>
      {priceFootnote ? (
        <div className="mt-1 text-sm text-[var(--muted-foreground)]">{priceFootnote}</div>
      ) : null}
      <p className="mt-3 text-sm text-[var(--muted-foreground)]">{tagline}</p>
      <ul className="mt-6 space-y-2 text-sm">
        {bullets.map((b) => (
          <li key={b}>{b}</li>
        ))}
      </ul>
      <div className="mt-auto pt-8">
        <Link
          href={ctaHref}
          className={
            'inline-block rounded-md px-4 py-2 font-medium ' +
            (emphasized
              ? 'bg-[var(--primary)] text-[var(--primary-foreground)]'
              : 'border border-[var(--border)]')
          }
        >
          {ctaLabel}
        </Link>
      </div>
    </div>
  );
}

function Workflow({
  label,
  steps,
  total,
}: {
  label: string;
  steps: string[];
  total: string;
}) {
  return (
    <div className="flex flex-col">
      <div className="text-xs uppercase tracking-wide text-[var(--muted-foreground)]">
        {label}
      </div>
      <ol className="mt-4 space-y-2 text-sm">
        {steps.map((step, i) => (
          <li key={i} className="flex gap-3">
            <span className="font-mono tabular-nums text-[var(--muted-foreground)]">
              {String(i + 1).padStart(2, '0')}
            </span>
            <span>{step}</span>
          </li>
        ))}
      </ol>
      <div className="mt-6 font-mono text-2xl">{total}</div>
    </div>
  );
}

function ScreenshotPair({
  light,
  dark,
  lightWidth,
  lightHeight,
  darkWidth,
  darkHeight,
  alt,
}: {
  light: string;
  dark: string;
  lightWidth: number;
  lightHeight: number;
  darkWidth: number;
  darkHeight: number;
  alt: string;
}) {
  return (
    <div className="rounded-lg border border-[var(--border)] overflow-hidden">
      <Image
        src={light}
        alt={alt}
        width={lightWidth}
        height={lightHeight}
        sizes="(min-width: 768px) 50vw, 100vw"
        className="block h-auto w-full dark:hidden"
      />
      <Image
        src={dark}
        alt={alt}
        width={darkWidth}
        height={darkHeight}
        sizes="(min-width: 768px) 50vw, 100vw"
        className="hidden h-auto w-full dark:block"
      />
    </div>
  );
}
