import Image from 'next/image';
import Link from 'next/link';

export const dynamic = 'force-dynamic';

export default function LandingPage() {
  return (
    <main>
      <section className="mx-auto max-w-3xl px-6 py-20">
        <h1 className="text-5xl font-semibold tracking-tight">
          Turn YouTube into notes you&apos;ll actually re-read.
        </h1>
        <p className="mt-6 text-lg text-[var(--muted-foreground)]">
          Paste a URL. Get a structured Markdown file — cliff notes, quotes with timestamps, and
          further reading — dropped straight into your Obsidian vault or Notion database.
        </p>

        <div className="mt-8 flex gap-3">
          <Link
            href="/sign-up"
            className="rounded-md bg-[var(--primary)] text-[var(--primary-foreground)] px-5 py-2.5 font-medium"
          >
            Try it free
          </Link>
        </div>

        <div className="mt-20 grid grid-cols-1 sm:grid-cols-3 gap-6">
          <Feature
            title="Writes to your vault, not another silo"
            body="A .md file with YAML frontmatter. Drop it in Obsidian, Notion, Logseq, or any folder of Markdown. No lock-in. Your notes live in your filesystem, indexed by the tool you already trust."
          />
          <Feature
            title="Timestamped quotes link back to YouTube"
            body="Every quoted passage in the summary includes a clickable timestamp. One click takes you back to the exact moment in the video — verify a claim, re-listen, or dig deeper."
          />
          <Feature
            title="Open-source core, bring your own key"
            body="The CLI, self-host backend, and Obsidian plugin are on GitHub. Run it yourself with a Gemini or Claude API key. Or skip the setup and use the hosted tier for $9.99/mo."
          />
        </div>
      </section>

      <section className="mx-auto max-w-5xl px-6 py-20">
        <h2 className="text-3xl font-semibold tracking-tight">What you actually get</h2>
        <p className="mt-3 text-[var(--muted-foreground)]">
          Paste a URL. Thirty seconds later, this is in your vault.
        </p>

        <div className="mt-10 grid grid-cols-1 md:grid-cols-2 gap-6">
          <ScreenshotPair
            light="/marketing/obsidian-frontmatter-light.webp"
            dark="/marketing/obsidian-frontmatter-dark.webp"
            lightWidth={2400}
            lightHeight={1462}
            darkWidth={2400}
            darkHeight={1431}
            alt="An Obsidian note generated by Kura, showing YAML frontmatter with title, channel, URL, tags, and a rendered cliff-notes outline."
          />
          <ScreenshotPair
            light="/marketing/obsidian-quotes-light.webp"
            dark="/marketing/obsidian-quotes-dark.webp"
            lightWidth={2400}
            lightHeight={1438}
            darkWidth={2400}
            darkHeight={1429}
            alt="The same Obsidian note, scrolled to the Quotes section, showing block quotes with clickable timestamped links back to the YouTube video."
          />
        </div>
      </section>
    </main>
  );
}

function Feature({ title, body }: { title: string; body: string }) {
  return (
    <div className="rounded-lg border border-[var(--border)] p-4">
      <h3 className="font-semibold">{title}</h3>
      <p className="mt-2 text-sm text-[var(--muted-foreground)]">{body}</p>
    </div>
  );
}

function ScreenshotPair({
  light,
  dark,
  lightWidth,
  lightHeight,
  darkWidth,
  darkHeight,
  alt,
}: {
  light: string;
  dark: string;
  lightWidth: number;
  lightHeight: number;
  darkWidth: number;
  darkHeight: number;
  alt: string;
}) {
  return (
    <div className="rounded-lg border border-[var(--border)] overflow-hidden">
      <Image
        src={light}
        alt={alt}
        width={lightWidth}
        height={lightHeight}
        sizes="(min-width: 768px) 50vw, 100vw"
        className="block h-auto w-full dark:hidden"
      />
      <Image
        src={dark}
        alt={alt}
        width={darkWidth}
        height={darkHeight}
        sizes="(min-width: 768px) 50vw, 100vw"
        className="hidden h-auto w-full dark:block"
      />
    </div>
  );
}
